### ISSUE TITLE
「redux-orm」を使用するようになったきっかけは何ですか？

### ISSUE THREAD

**Issue by jungpaeng** [kra8/react-redux-lab#1]
「redux-orm」を使用するためのデータを探していました。
そんな中、当該repoを発見することができました。

「normalizr」から「redux-orm」に変換することになったきっかけについて聞いてもいいですか？
この二つの違いを知ってみたいが、資料が出ません。

**Comment by kra8** [comment]
こんにちは。
きっかけは、normalizrとImmutableJSの相性の悪さを感じたからです。

「normalizr」は正規化することに特化しており、そのあとのデータ扱いをサポートしていませんでした。
さらに、正規化されているとはいえ、複雑化した索引付けされているようなデータの塊を扱うことは人間には大変だと思ったのです。

一方、「redux-orm」はリレーショナルに特化したライブラリで、正規化も実用程度にはサポートされており、さらにImmutableなModelを利用できるので「normalizr」ではなく「redux-orm」を使おうといたりました。

ですので違いといえば、「正規化するライブラリ」か「正規化したデータを扱うライブラリ」かの違いだと思います。

**Comment by jungpaeng** [comment]
知らせてくれてありがとうございます。
