### ISSUE TITLE
How to change saving data format in redux store?

### ISSUE THREAD

**Issue by Pewww** [kra8/react-redux-lab#2]
![image](https://user-images.githubusercontent.com/23455736/57981613-9b313880-7a74-11e9-9b97-41b1fa123e06.png)

Hi kra8!
I'm following your project and learning about 'redux-orm'.
After the execution of saving 'ORM' data in 'redux store', every data's form changes as the picture I added.
But, I don't really want and need that basic format.
So, I want to know how to change the basic format to my custom format like this.

- Basic -
Feed: {
  items: [1, 2, 3],
  itemsById: {1: {}, 2: {}, 3: {}},
  indexes: {},
  meta: {maxId: 789}
}

- To Custom Format -
Feed: {
  ids: [1, 2, 3],
  data: {1: {}, 2: {}, 3: {}}
}

If you know the answer, please tell me!
Thank you so much~

- 翻訳 -
こんにちは!
あなたのプロジェクトをフォローし,"Redux-orm"について学んでいます。
"Redux store"に"ORM"データを保存すると,追加した画像のように全てのデータの形式が変わります。
でも,そんな基本的な形式は,あまり欲しくないし,必要もない。
基本フォーマットをカスタムフォーマットに変更する方法を教えてください。
(上記のデータ形式と同じだ)
もし答えが分かったら,私に言ってください!
ありがとうございました~

**Comment by kra8** [comment]
Hi Pewww, thank you for Issue.

Why need to custom format?

`redux-orm` has database. You need a database to work with models.
``` js
const session = orm.session(DBState);
const Book = session.Book;
Book.withId(1).update({ name: 'Clean Code' });
//...
```
Maybe need a decided database to use `redux-orm`.
So, you can customize the state of redux store, but need to the original format to use session.
And if you also use selectors, you have to create them yourself.

If you do not need API of `redux-orm`, but just want to normalize, you may want to use [normalizr](https://github.com/paularmstrong/normalizr).

**Comment by Pewww** [comment]
Thanks for your answer, kra8!!
